# Generated by Django 3.2.4 on 2021-06-13 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('conversationId', models.IntegerField(primary_key=True, serialize=False)),
                ('storeId', models.IntegerField()),
                ('operatorId', models.IntegerField()),
                ('clientId', models.IntegerField()),
                ('operatorGroup', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.IntegerField(blank=True, null=True)),
                ('payload', models.TextField(blank=True, max_length=300, null=True)),
                ('userId', models.IntegerField()),
                ('utc_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('sent', 'Sent')], max_length=20)),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='api.conversation')),
            ],
        ),
    ]
