# Generated by Django 3.2.4 on 2021-06-13 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='payload',
            field=models.TextField(default=2, max_length=300, validators=[django.core.validators.RegexValidator('[[:alpha:]]+\\d+\\W+\\_\\-\\\\/\\~\\@\\#\\$\\%\\^\\&\\*\\(\\)\\!\\?')]),
            preserve_default=False,
        ),
    ]
