# Generated by Django 3.2.4 on 2021-06-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_chat_payload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='utc_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
