# Generated by Django 3.2.4 on 2021-06-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210613_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='chatId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='payload',
            field=models.TextField(max_length=300),
        ),
    ]
